
CREATE USER 'junior'@'localhost'  identified BY '123456';
-- MODIFICO SU CONTRASEÑA

-- LO PUEDO ELIMINAR CON DROP
 -- DROP USER 'junior'@'localhost';
-- VERIFICO QUE PERMISOS TIENE
SELECT * FROM mysql.user WHERE USER LIKE 'Pep%';
SHOW GRANTS FOR 'Pepe'@'localhost';
-- OTORGO PERMISOS DE LECTURA, INSERCION Y MODIFICACION PARA TODAS LAS TABLAS
-- PERO NO PARA ELIMINACION DE REGISTROS
GRANT SELECT, INSERT, UPDATE ON proyecto_final.* TO 'junior'@'localhost';