-- DESACTIVAMOS AUTO COMMIT
use proyecto_final;
SELECT @@AUTOCOMMIT = 0;

-- TENGO LA REFERENCIA DE COMO ESTA INICIALMENTE LA TABLA 'factura'
SELECT * FROM factura;
START TRANSACTION;
DELETE FROM factura
-- ELIMINAMOS FACTURAS CUYO VALOR TOTAL OSCILE ENTRE 2000 Y 3000
WHERE valorTotal BETWEEN 2000 AND 3000
-- UTILIZO EL ID YA QUE ES UNA COLUMNA CLAVE Y FACILITA LA ELIMINACION DEL REGISTRO
 AND idFactura > 0; -- Utiliza una columna clave;
 -- VER LA TABLA ACTUALIZADA
SELECT * FROM factura;
-- ROLLBACK;