insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (1, 15, 'Compactor', 'Blue', 4);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (2, 17, 'Crawler', 'Mauv', 43);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (3, 14, 'Dump Truck', 'Purple', 17);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (4, 19, 'Grader', 'Khaki', 5);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (5, 7, 'Dragline', 'Indigo', 43);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (6, 19, 'Excavator', 'Puce', 72);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (7, 3, 'Bulldozer', 'Violet', 80);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (8, 13, 'Dump Truck', 'Teal', 17);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (9, 7, 'Crawler', 'Aquamarine', 50);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (10, 12, 'Backhoe', 'Red', 40);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (11, 20, 'Excavator', 'Indigo', 16);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (12, 5, 'Skid-Steer', 'Turquoise', 13);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (13, 8, 'Skid-Steer', 'Aquamarine', 51);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (14, 17, 'Skid-Steer', 'Mauv', 97);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (15, 19, 'Trencher', 'Purple', 51);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (16, 12, 'Backhoe', 'Khaki', 81);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (17, 18, 'Compactor', 'Teal', 90);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (18, 9, 'Bulldozer', 'Yellow', 1);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (19, 15, 'Grader', 'Crimson', 82);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (20, 16, 'Dragline', 'Goldenrod', 77);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (21, 10, 'Scraper', 'Turquoise', 71);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (22, 15, 'Backhoe', 'Mauv', 32);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (23, 15, 'Backhoe', 'Mauv', 60);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (24, 18, 'Compactor', 'Blue', 93);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (25, 2, 'Compactor', 'Mauv', 70);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (26, 9, 'Dump Truck', 'Teal', 95);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (27, 8, 'Dump Truck', 'Mauv', 9);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (28, 5, 'Excavator', 'Aquamarine', 64);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (29, 10, 'Trencher', 'Maroon', 89);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (30, 3, 'Scraper', 'Purple', 25);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (31, 7, 'Compactor', 'Fuscia', 67);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (32, 4, 'Compactor', 'Violet', 42);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (33, 13, 'Compactor', 'Maroon', 19);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (34, 5, 'Crawler', 'Pink', 87);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (35, 20, 'Trencher', 'Aquamarine', 94);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (36, 19, 'Dump Truck', 'Purple', 97);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (37, 7, 'Dragline', 'Puce', 35);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (38, 1, 'Crawler', 'Teal', 83);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (39, 2, 'Grader', 'Yellow', 96);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (40, 19, 'Scraper', 'Red', 39);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (41, 10, 'Grader', 'Orange', 28);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (42, 17, 'Dump Truck', 'Mauv', 18);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (43, 19, 'Grader', 'Maroon', 15);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (44, 13, 'Excavator', 'Khaki', 36);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (45, 11, 'Compactor', 'Indigo', 67);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (46, 2, 'Dump Truck', 'Aquamarine', 88);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (47, 18, 'Backhoe', 'Violet', 84);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (48, 2, 'Trencher', 'Mauv', 16);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (49, 20, 'Backhoe', 'Crimson', 45);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (50, 4, 'Excavator', 'Blue', 30);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (51, 17, 'Compactor', 'Indigo', 91);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (52, 16, 'Compactor', 'Orange', 42);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (53, 8, 'Bulldozer', 'Goldenrod', 24);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (54, 7, 'Scraper', 'Purple', 84);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (55, 18, 'Skid-Steer', 'Indigo', 9);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (56, 4, 'Backhoe', 'Pink', 29);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (57, 7, 'Skid-Steer', 'Pink', 63);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (58, 7, 'Grader', 'Puce', 59);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (59, 3, 'Dragline', 'Violet', 87);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (60, 13, 'Skid-Steer', 'Goldenrod', 48);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (61, 3, 'Backhoe', 'Khaki', 59);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (62, 18, 'Excavator', 'Teal', 64);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (63, 12, 'Dump Truck', 'Puce', 26);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (64, 20, 'Grader', 'Yellow', 26);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (65, 17, 'Compactor', 'Puce', 1);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (66, 5, 'Crawler', 'Mauv', 87);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (67, 7, 'Crawler', 'Teal', 82);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (68, 7, 'Grader', 'Blue', 9);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (69, 17, 'Crawler', 'Crimson', 75);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (70, 17, 'Dump Truck', 'Red', 57);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (71, 4, 'Bulldozer', 'Blue', 45);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (72, 13, 'Dump Truck', 'Violet', 84);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (73, 17, 'Excavator', 'Fuscia', 55);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (74, 1, 'Crawler', 'Khaki', 27);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (75, 14, 'Compactor', 'Violet', 46);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (76, 9, 'Bulldozer', 'Aquamarine', 20);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (77, 15, 'Excavator', 'Turquoise', 24);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (78, 20, 'Compactor', 'Purple', 56);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (79, 7, 'Trencher', 'Aquamarine', 36);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (80, 9, 'Grader', 'Purple', 33);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (81, 7, 'Dragline', 'Pink', 18);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (82, 19, 'Excavator', 'Pink', 84);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (83, 5, 'Grader', 'Goldenrod', 21);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (84, 5, 'Crawler', 'Purple', 8);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (85, 13, 'Backhoe', 'Turquoise', 55);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (86, 19, 'Dragline', 'Orange', 68);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (87, 12, 'Crawler', 'Violet', 92);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (88, 3, 'Dragline', 'Pink', 58);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (89, 16, 'Grader', 'Aquamarine', 34);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (90, 12, 'Crawler', 'Pink', 65);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (91, 16, 'Skid-Steer', 'Pink', 9);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (92, 7, 'Scraper', 'Turquoise', 42);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (93, 12, 'Scraper', 'Orange', 26);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (94, 6, 'Bulldozer', 'Khaki', 62);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (95, 16, 'Backhoe', 'Turquoise', 31);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (96, 13, 'Bulldozer', 'Khaki', 42);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (97, 16, 'Grader', 'Turquoise', 99);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (98, 11, 'Scraper', 'Red', 1);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (99, 9, 'Trencher', 'Purple', 70);
insert into articulo (idArticulo , vendId , descripcionArticulo , color , stock ) values (100, 15, 'Dragline', 'Fuscia', 7);

select * from articulo;